/** Lignes anonymisées — structure export « Investissement Placement ». */
export const PLACEMENT_COMMANDES_SAMPLE_ROWS: Record<string, unknown>[] = [
  {
    "Nom complet Investisseur": "DUPONT Jean",
    "Email Investisseur": "jean.dupont@example.com",
    "Type Produit": "Assurance Vie",
    Partenaire: "VIE PLUS Assureur",
    "Libellé Produit": "Cristalliance Avenir Placement Multi-supports",
    "Numéro de Contrat": "9E 271740658",
    "Date Effet": "18/11/2024",
    "Etat Commande": "En-cours",
    "dont Versement Initial En-Cours": 1500,
    "Programmation de Versements?\r\nFréquence?": "Aucune",
  },
  {
    "Nom complet Investisseur": "10 LEGRAND Paul",
    "Email Investisseur": "paul.legrand@example.com",
    "Type Produit": "SCPI rendement",
    Partenaire: "ALDÉRAN  Gestionnaire de biens",
    "Libellé Produit": "Comète CIF",
    "Numéro de Contrat": "ALDE202602031334COM",
    "Date Effet": "01/03/2023",
    "Type du dernier Mouvement VC": "Versement initial",
    "Date du dernier Mouvement VC": "01/03/2023",
    "Montant du dernier Mouvement VC": 12000,
    "Montant Versement VC cumulé sur la période": 12000,
    "Etat Commande": "En-cours",
    "Programmation de Versements?\r\nFréquence?": "Aucune",
  },
  {
    "Nom complet Investisseur": "BERNARD Luc",
    "Type Produit": "Assurance Vie",
    Partenaire: "APICIL Assureur",
    "Libellé Produit": "Transitions Europe (ALPSI)",
    "Numéro de Contrat": "4055352",
    "Date Effet": "16/07/2020",
    "Date de Sortie": "24/02/2025",
    "Etat Commande": "Close",
    "dont Versement Initial En-Cours": 9000,
    "Programmation de Versements?\r\nFréquence?": "Aucune",
  },
];
