/** Lignes anonymisées — structure export Finzzle « Mon Organisation ». */
export const MON_ORGANISATION_SAMPLE_ROWS: Record<string, unknown>[] = [
  {
    Nom: "DUPONT",
    Prénom: "Jean",
    "Niveau hiérarchique": "00",
    Parrain: "LEGRAND Paul",
    "Date Entrée": "10/07/2018",
    Adresse: "12 rue des Acacias",
    "Code Postal": "75001",
    Ville: "Paris",
    Pays: "France",
    "Mail Information": "jean.dupont@example.com",
    "Téléphone Mobile": "0612345678",
    "(Niveau) Nom prénom du Consultant": "DUPONT Jean",
  },
  {
    Nom: "BERNARD",
    Prénom: "Luc",
    "Niveau hiérarchique": "01",
    Parrain: "DUPONT Jean",
    "Date Entrée": "20/12/2021",
    Adresse: "8 place du Marché",
    "Code Postal": "69002",
    Ville: "Lyon",
    Pays: "France",
    "Mail Information": "luc.bernard@example.com",
    "Téléphone Mobile": '="+33600000002"',
    "(Niveau) Nom prénom du Consultant": "/__ (01) BERNARD Luc",
  },
  {
    Nom: "MARTIN",
    Prénom: "Sophie",
    "Niveau hiérarchique": "02",
    Parrain: "BERNARD Luc",
    "Date Entrée": "17/09/2025",
    Adresse: "5 avenue du Parc",
    "Code Postal": "33000",
    Ville: "Bordeaux",
    Pays: "France",
    "Mail Information": "sophie.martin@example.com",
    "Téléphone Mobile": "+ () 06.12.34.56.78",
    "(Niveau) Nom prénom du Consultant": "/____ (02) MARTIN Sophie",
  },
];
